version: "3.9"

services:
  nginx:
    image: nginx:alpine
    container_name: reverse-proxy
    restart: unless-stopped
    ports:
      - "10881:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

  frontend:
    build:
      context: ./fe-portal
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    expose:
      - "3000"
    env_file: ./fe-portal/.env
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    env_file: ./backend/.env
    volumes:
      - ./backend/logs:/usr/src/app/logs
    expose:
      - "5000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
